### ISSUE TITLE
Process Updates

### ISSUE THREAD

**Issue by Seanv554** [CS149-3/homework2#21]
My ShortestRemainingTime algorithm needs the following accessors in the Process class in order to function properly:

float getStartTime()
String getName()

Please make sure these are present when you merge update_ShortestRemainingTime

**Comment by flip40** [comment]
Are you ready for me to merge it I take it?

**Comment by Seanv554** [comment]
Not quite, I still need to implement the statistics gathering. I will let you know when that's done.

**Comment by flip40** [comment]
Ok. I'll add those getter functions to Process (or at lest, getStartTime, getName was added recently).

**Comment by flip40** [comment]
#22 solves this for the getStartTime function. An Earlier merge of #19 (FCFS) included a change that solved the getName function (just noting that this issue was solved and by what).
